version: '3.3'
services:
  sut:
    build:
     context: .
     args:
      - ORIGINAL_IMAGE=alpine
      - ORIGINAL_CMD=/bin/sh
    volumes:
      - .:/opt
    command: /opt/run_tests.sh
    environment:
      - GIT_URL=https://github.com/arnaudlacour/giterize.git
      - GIT_PATH=tests
      - VERBOSE=true