version: '3.3'
services:
  sut:
    image: arnaudlacour/giterize:${CACHE_TAG}
    volumes:
      - .:/opt
    command: /opt/run_tests.sh
    environment:
      - GIT_URL=https://github.com/arnaudlacour/giterize.git
      - GIT_PATH=tests
      - VERBOSE=true