#!/bin/bash
docker pull ${image}
originalEntrypoint=$( docker image inspect ${image} --format '{{join .Config.Entrypoint " "}}' )
originalCmd=$( docker image inspect ${image} --format '{{join .Config.Cmd " "}}' )
docker build \
    --build-arg "ORIGINAL_ENTRYPOINT=${originalEntrypoint}" \
    --build-arg "ORIGINAL_CMD=${originalCmd}" \
    --build-arg "ORIGINAL_IMAGE=${image}" \
    -f ${DOCKERFILE_PATH} \
    -t ${IMAGE_NAME} .
    .